import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#000000',
          light: '#60A5FA',
          main: '#3B82F6',
          dark: '#2563EB',
        },
        secondary: {
          DEFAULT: '#725b26',
          light: '#5EEAD4',
          main: '#14B8A6',
          dark: '#0D9488',
        },
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#f8f9ff',
        'secondary-container': '#fcdc9a',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'on-secondary-fixed': '#251a00',
        'surface-variant': '#d3e4fe',
        'tertiary-fixed-dim': '#c4c7c9',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'on-primary': '#ffffff',
        'on-secondary-container': '#775f29',
        'inverse-on-surface': '#eaf1ff',
        error: '#ba1a1a',
        'on-tertiary-fixed': '#191c1e',
        'on-primary-fixed-variant': '#3f465c',
        'tertiary-fixed': '#e0e3e5',
        'tertiary-container': '#191c1e',
        'on-background': '#0b1c30',
        tertiary: '#000000',
        'error-container': '#ffdad6',
        'inverse-primary': '#bec6e0',
        'primary-fixed-dim': '#bec6e0',
        'surface-container-high': '#dce9ff',
        surface: '#f8f9ff',
        'inverse-surface': '#213145',
        'on-secondary': '#ffffff',
        outline: '#76777d',
        'primary-fixed': '#dae2fd',
        'on-secondary-fixed-variant': '#594410',
        'on-primary-fixed': '#131b2e',
        'on-error-container': '#93000a',
        'surface-dim': '#cbdbf5',
        'primary-container': '#131b2e',
        background: '#f8f9ff',
        'secondary-fixed-dim': '#e2c383',
        'surface-container-highest': '#d3e4fe',
        'outline-variant': '#c6c6cd',
        'on-primary-container': '#7c839b',
        'on-surface-variant': '#45464d',
        'on-surface': '#0b1c30',
        'surface-tint': '#565e74',
        'on-tertiary-fixed-variant': '#444749',
        'secondary-fixed': '#ffdf9d',
        'on-tertiary-container': '#818486',
        neutral: {
          white: '#FFFFFF',
          gray50: '#F9FAFB',
          gray100: '#F3F4F6',
          gray900: '#111827',
        },
      },
      fontFamily: {
        primary: ['var(--font-hanken)', 'sans-serif'],
        secondary: ['var(--font-playfair)', 'serif'],
        'label-sm': ['var(--font-hanken)', 'sans-serif'],
        'headline-lg': ['var(--font-playfair)', 'serif'],
        'display-lg': ['var(--font-playfair)', 'serif'],
        'headline-lg-mobile': ['var(--font-playfair)', 'serif'],
        'headline-md': ['var(--font-playfair)', 'serif'],
        'body-lg': ['var(--font-hanken)', 'sans-serif'],
        'body-md': ['var(--font-hanken)', 'sans-serif'],
      },
      spacing: {
        section: '5rem',
        container: '1.5rem',
        'section-padding': '120px',
        'container-max': '1280px',
        'stack-lg': '32px',
        'margin-mobile': '20px',
        gutter: '32px',
        'stack-sm': '8px',
        'stack-md': '16px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '600' }],
        'headline-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '500' }],
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['36px', { lineHeight: '1.2', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0.01em', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
      },
      borderRadius: {
        sm: '0.375rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
      },
      boxShadow: {
        sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        md: '0 4px 6px -1px rgb(0 0 0 / 0.1)',
        lg: '0 10px 15px -3px rgb(0 0 0 / 0.1)',
        glass: '0 8px 32px 0 rgba(31, 38, 135, 0.15)',
      },
      screens: {
        mobile: '320px',
        tablet: '768px',
        desktop: '1024px',
        wide: '1280px',
      },
    },
  },
  plugins: [],
};

export default config;
